server:
  port: 8082
logging:
  level:
    ROOT: INFO
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      #ddl-auto: none
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/bookstore
    username: postgres
    password: admin
    #    username: webedi
    #    password: 111111
    driverClassName: org.postgresql.Driver

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: mm
  cloud:
    zoo


bookstore:
  cache:
    url: http://localhost:8083

kafka:
  bootstrap-address: localhost:9092
  topic-name: my_test


