server:
  port: 8082

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
      #ddl-auto: none
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/bookstore
#    username: webedi
#    password: 111111
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver